### ISSUE TITLE
Update robots.txt for every stable release

### ISSUE THREAD

**Issue by est31** [rust-lang/promote-release#17]
I'd heard that @imperio and @QuietMisdreavus from the docs team wanted to improve SEO for official rust documentation. So I dug a little and found that doc.rust-lang.org has a [robots.txt](https://doc.rust-lang.org/robots.txt). If we could list all stable releases in robots.txt, we could achieve the SEO improvements that the docs team wanted. Some things I found out:

* Apparently you can't create any regexes for paths in robots.txt so you need to list all stable releases (googling told me).
* All doc.rlo content including the robots.txt is hosted on S3.
* rust-central-station seems to be uploading the docs to that S3 storage

It would be awesome if:

- [ ] robots.txt got amended with the past releases
- [ ] rust-central-station would update robots.txt on every release automatically

**Comment by jyn514** [comment]
cc @jsha, this seems like something you'd be interested in

**Comment by jsha** [comment]
Thanks for the tag @jyn514! I'd be curious what the original problems were with SEO for doc.rust-lang.org. From context I'm guessing it was a problem of Google choosing the wrong canonical URL, like we're trying to solve for docs.rs at https://github.com/rust-lang/docs.rs/issues/1438? Perhaps in 2018 it was the case that each release was published at a versioned URL and there was no "current" URL like `https://doc.rust-lang.org/std/`?

Also just to confirm, the current contents of https://doc.rust-lang.org/robots.txt are the same as [shown in @follower's comment](https://github.com/rust-lang/promote-release/issues/17#issuecomment-703538488). It looks like the current robots.txt actually does block the versioned URL for each stable release, by blocking `/1.`.

I have access to the Google Search Console for `rust-lang.org`. Quantitatively, of the top 1000 pages Google sends people to, 754 are `doc.rust-lang.org`. Of those: 21 have `/beta/` in the URL (mostly rust-by-example pages). 6 have `/nightly/` in the URL. 327 have `/std/` in the URL. 5 have a version number (e.g. `/1.0.0/`) in the URL. The rest, roughly speaking, are pages from the various books. So, overall, if the problem is "Google sends people to a versioned page and that version isn't the latest," I think this SEO problem has been solved.

Also, qualitatively, my experience has been that search results for pages on doc.rust-lang.org usually point to the right page.

So I propose to close this issue unless there are specific queries that someone can cite as giving wrong results.

**Comment by jyn514** [comment]
amazing, thanks @jsha! going to close this unless someone runs into trouble again :)

**Comment by est31** [comment]
I opened it 5 years ago but I *think* the problem was that when you looked for some concept on rust, google would link to a random version's rustdoc, like say 1.20.0. Which would then surprise users when not everything was available.

Ultimately, no idea how or when this got resolved. I opened this back then to organize discussion on the issue but it seems the people who originally expressed these desires did not want to participate, at least here. Shrug, closing is okay I guess.
